version: "3.8"

services:
  web:
    build: .
    container_name: angia-website
    restart: unless-stopped
    ports:
      - "80:80"
    networks:
      - angia-network

networks:
  angia-network:
    driver: bridge
