version: "3.8"

services:
  web:
    build: .
    container_name: angia-website
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./dist:/usr/share/nginx/html
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - angia-network

networks:
  angia-network:
    driver: bridge
