name: Deploy to Production

on:
  push:
    branches: [main]

env:
  REPO_NAME: angia-website

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Add host key
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H ${{ secrets.DROPLET_IP }} >> ~/.ssh/known_hosts

      - name: Deploy to Digital Ocean
        env:
          DROPLET_IP: ${{ secrets.DROPLET_IP }}
        run: |
          ssh root@$DROPLET_IP << 'ENDSSH'
            # Navigate to home directory
            cd /root
            
            # Clone repository if it doesn't exist
            if [ ! -d "$REPO_NAME" ]; then
              git clone https://github.com/Gbanya-Michael/angia-website.git
            fi
            
            # Navigate to project directory and pull latest changes
            cd $REPO_NAME
            git pull origin main
            
            # Clean up Docker resources
            docker system prune -f
            
            # Ensure docker-compose is available
            if ! command -v docker-compose &> /dev/null; then
              apt update
              apt install -y docker-compose
            fi
            
            # Start the application
            docker-compose down
            docker-compose up --build -d
          ENDSSH
